version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: sarathi-mongo-dev
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data_dev:/data/db
    environment:
      MONGO_INITDB_DATABASE: sarathi

  redis:
    image: redis:7-alpine
    container_name: sarathi-redis-dev
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data_dev:/data

volumes:
  mongo_data_dev:
  redis_data_dev:

